# Generated by Django 4.1.6 on 2023-08-17 18:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_institution', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=100)),
                ('course_dept', models.CharField(max_length=100, null=True)),
                ('course_num', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('course_grade', models.CharField(blank=True, max_length=1)),
                ('course_delivery', models.CharField(blank=True, max_length=10)),
                ('syllabus_url', models.URLField(blank=True, null=True)),
                ('credit_hours', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UVA_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_dept', models.CharField(max_length=100)),
                ('course_num', models.PositiveIntegerField()),
                ('credit_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Viable_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_dept', models.CharField(blank=True, max_length=100, null=True)),
                ('course_num', models.PositiveIntegerField(null=True)),
                ('course_grade', models.CharField(blank=True, max_length=1, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'A'), ('D_LowGrade', 'D_LowGrade'), ('D_BadFit', 'D_BadFit'), ('P', 'P')], default='P', max_length=10)),
                ('credit_hours', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('reviewer_comment', models.CharField(max_length=300, null=True)),
                ('credits_approved', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('foreign_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransferGuide.course')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uva_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TransferGuide.uva_course')),
            ],
        ),
    ]
