# Generated by Django 4.1.5 on 2023-03-23 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("TransferGuide", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_institution",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "course_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "course_dept_num",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("course_grade", models.CharField(blank=True, max_length=1, null=True)),
                ("approved", models.CharField(default="P", max_length=1)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
