# Generated by Django 4.1.5 on 2023-03-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0002_course"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="username",),
    ]
