# Generated by Django 4.1.5 on 2023-03-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0003_course_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="name", new_name="username",
        ),
    ]
