# Generated by Django 4.1.5 on 2023-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0003_remove_course_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
