# Generated by Django 4.1.5 on 2023-03-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0003_remove_course_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_delivery",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
