# Generated by Django 4.1.5 on 2023-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0004_rename_name_course_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="course_description",),
        migrations.RemoveField(model_name="course", name="course_number",),
        migrations.RemoveField(model_name="course", name="course_url",),
        migrations.AddField(
            model_name="course",
            name="course_dept_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_grade",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
