# Generated by Django 4.1.5 on 2023-03-23 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0005_course_syllabus_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="credit_hours",
            field=models.PositiveIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
