# Generated by Django 4.1.5 on 2023-03-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0006_course_credit_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="approved",
            field=models.CharField(default="P", max_length=1),
        ),
    ]
