# Generated by Django 4.1.5 on 2023-03-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0008_viable_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
