# Generated by Django 4.1.5 on 2023-03-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0009_course_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="status",),
    ]
