# Generated by Django 4.1.5 on 2023-03-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0010_remove_course_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="approved", new_name="status",
        ),
    ]
