# Generated by Django 3.2.18 on 2023-04-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0011_rename_approved_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='equivalent',
            field=models.CharField(default='', max_length=30),
        ),
    ]
