# Generated by Django 4.1.6 on 2023-04-06 00:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TransferGuide', '0011_rename_approved_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UVA_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_dept', models.CharField(max_length=100)),
                ('course_num', models.PositiveIntegerField()),
                ('credit_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'A'), ('D', 'D'), ('P', 'P')], default='P', max_length=1)),
                ('credit_hours', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('foreign_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransferGuide.course')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uva_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TransferGuide.uva_course')),
            ],
        ),
    ]