# Generated by Django 3.2.18 on 2023-04-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0012_course_equivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='why_denied',
            field=models.CharField(default='', max_length=200),
        ),
    ]
