# Generated by Django 3.2.18 on 2023-04-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0013_course_why_denied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='equivalent',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='why_denied',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
