# Generated by Django 4.1.6 on 2023-04-06 13:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TransferGuide', '0014_auto_20230401_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viable_course',
            old_name='course_dept_num',
            new_name='course_dept',
        ),
        migrations.RemoveField(
            model_name='course',
            name='equivalent',
        ),
        migrations.RemoveField(
            model_name='course',
            name='why_denied',
        ),
        migrations.AddField(
            model_name='viable_course',
            name='course_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_delivery',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_grade',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
