# Generated by Django 4.1.6 on 2023-04-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0012_uva_course_remove_course_course_dept_num_and_more'),
        ('TransferGuide', '0015_uva_course_and_more'),
    ]

    operations = [
    ]
