# Generated by Django 4.1.6 on 2023-04-06 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0016_merge_20230406_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_dept_num',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='course_dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_num',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
