# Generated by Django 4.1.6 on 2023-04-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0017_remove_course_course_dept_num_remove_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viable_course',
            name='uva_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TransferGuide.uva_course'),
        ),
    ]
