# Generated by Django 4.1.6 on 2023-04-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0018_viable_course_uva_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viable_course',
            name='uva_course',
        ),
    ]
