# Generated by Django 4.1.6 on 2023-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0019_remove_viable_course_uva_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reviewer_comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
