# Generated by Django 4.1.5 on 2023-04-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TransferGuide", "0020_request_reviewer_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("D-LowGrade", "D-LowGrade"),
                    ("D-BadFit", "D-BadFit"),
                    ("P", "P"),
                ],
                default="P",
                max_length=10,
            ),
        ),
    ]
