# Generated by Django 3.2.18 on 2023-04-18 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0022_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='credits_approved',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
